//
//  Job.swift
//  Get_To_It_iOS
//
//  Created by Richard Blakeney-Williams on 17/05/16.
//  Copyright © 2016 Get To It Ltd. All rights reserved.
//

import Foundation
import GoogleMaps


class Job{
    
//    var jobId: NSUUID //This is going to be generated by FireBase...
//    var name: NSString
//    var locationLat: Double
//    var locationLong: Double
//    var picture: NSURL
//    var description: NSString
//    var categories: NSString
//    var totalNumberOfHoursRequired: Int
//    var totalNumberOfHoursCompleted: Int
//    var time: NSDate
//    var completed: Bool
//    var workerRating: Double
//    var employerRating: Double
//    var employer_id: NSString
//    var worker_id: NSString
    
    
    
//    init(name: NSString,startTime: NSDate, endTime: NSDate, categories: [Category], description: NSString, longtitude: Double, latitude: Double){
////        self.id = NSUUID()
////        self.name = name
////        self.startTime = startTime
////        self.categories = categories
////        self.endTime = endTime
////        self.description = description
////    
////        let marker = GMSMarker()
////        marker.position = CLLocationCoordinate2DMake(longtitude,latitude)
////        self.location = marker
////        
////        let timeBetweenInHours = Int(startTime.timeIntervalSinceDate(endTime))/3600
////        self.totalNumberOfHours = timeBetweenInHours
//    }
    
    
    
    
}